%%% This script change the 864*14 psc generated by ROIExtrate function into
%%% a 4 bar image that reprent brain activity in working memory tasks.

function HCPSm4WmTaskComparisionBarGraph(roiDataPath,outputFigureFolder)
load(roiDataPath)
colorArray =  {[0.4118 0.7373 0.4196],[0.3765 0.6431 0.8157],[0.8510 0.1569 0.1333],[1 0.5882 0]};
gapInd = []
%xtick = [1,2,3,4];
%xticklabels = {'Faces','Bodies','Tools','Places'};
outputFigurePath = [outputFigureFolder '/' fpp.bids.checkNameValue(roiDataPath,'desc') '.png']
newcondNames = condNames(7:end);
newpscbySub = pscBySub(:,7:end); 
averagepsc = (newpscbySub(:,1:4) + newpscbySub(:,5:end))/2;
newpscSD = pscRunwiseStdErr(7:end);
avepscSD = (newpscSD(1:4)+newpscSD(5:end))/2;
figure('Position',[200 500 600 400]);
[b,~,e,barInd] = fpp.util.barColor(averagepsc,colorArray,avepscSD,[],0);
gca = gcf().CurrentAxes;
gca.XColor = [0,0,0];
gca.FontSize = 30;
%gca.XTick = xtick;
%gca.XTickLabel = xticklabels;
gca.FontSize = 18;
ylabel('PSC')
saveas(gcf,outputFigurePath);
%fpp.util.fileParts('/mnt/sml_share/HCP/derivatives/fpp/group/Sm4TPContrastsResults/space-fsLR_res-2_den-32k_desc-handDrawnLTPThrP6workingmemoryBodyVsAllOthersTop5PctN864Sm4_roiData.mat')
end
